parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your mysql server
        # driver: 'pdo_mysql'
        # server_version: '5.7'
        # charset: utf8mb4
        # default_table_options:
            # charset: utf8mb4
            # collate: utf8mb4_unicode_ci
        # url: '%env(resolve:DATABASE_URL)%'

        # configure these for your sqlite server
        # driver: 'pdo_sqlite'
        # server_version: '3.15'
        # charset: UTF8
        # url: '%env(resolve:DATABASE_URL)%'

        default_connection: default

        connections:
            default:
                driver: '%database_driver%'
                dbname: '%database_name%'
                host: '%database_host%'
                port: '%database_port%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8
                path: '%database_path%'
                server_version: '%database_version%'

    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
